### ISSUE TITLE
Applying Fonts

### ISSUE THREAD

**Issue by koya-tech** [Cornerstone-CICCC/web-1-final-project-team3-final#10]
From chloe comment
https://github.com/Cornerstone-CICCC/web-1-final-project-team3-final/pull/8#discussion_r18441460494

We need to apply a second font(Nunito) in about service and header/footer.

After merge these below PR, I will do issue
https://github.com/Cornerstone-CICCC/web-1-final-project-team3-final/pull/7
https://github.com/Cornerstone-CICCC/web-1-final-project-team3-final/pull/8

**Comment by hello-chloe-seoyeong** [comment]
- branch: pages/portfolio, msgboxAndHeaderFooter

These parts are also need to change the same issue. 
After merging your PR and defined fonts, I will modify.
It would be better to import "google font link" into reset or variables and use it. 
Let me know when fonts are ready. 👍
