### ISSUE TITLE
can not see hamburger menu in only home

### ISSUE THREAD

**Issue by koya-tech** [Cornerstone-CICCC/web-1-final-project-team3-final#16]
like this image, can not see hamburger menu in **only home**

<img width="285" alt="Screenshot 2024-11-17 134139" src="https://github.com/user-attachments/assets/abe4aa2e-c001-4a54-a755-c84dc94dc5e4">

**Comment by hello-chloe-seoyeong** [comment]
I will check!

**Comment by hello-chloe-seoyeong** [comment]
Fixed and created pull request. 
https://github.com/Cornerstone-CICCC/web-1-final-project-team3-final/pull/18
